package gui;


import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JList;


import utils.logging.Log;
import utils.tuples.TupleFour;

/*
 * This is part of the BODNetLogo program which integrates BOD with NetLogo,
 * please see the README files for this directory for more information
 * Michael Brooks
 */

/*
 * This code was originally auto generated by the NETBEANS IDE, gui creator.
 * The auto generator code only covers the positioning and specification of the GUI elements
 * The functionality of each element was later added manually
 */

@SuppressWarnings("serial")
public class AddAgent extends javax.swing.JFrame {

    /**
     * Creates new form addAgent
     * @param listOfBreeds 
     */
	

    private String[] values;
	
	TupleFour<String[], Integer, String, String[]> agent = null;
	
	private MainUI main;
	
    public AddAgent(MainUI x, JList<String> listOfBreeds) {
        this.main = x;
    	initComponents();
        
        
    }

    public AddAgent(MainUI mainUI, JList<String> listOfBreeds, int selectedIndex) {
        this.main = mainUI;
		this.agent = mainUI.agents[listOfBreeds.getSelectedIndex()];
        initComponents();
		setAgentValues();
	}
    
	private void setAgentValues()	{
    	if (agent !=null)	{
    		pluralBreedNameTextBox.setText(agent.First[1]);
    		singleBreedNameTextBox.setText(agent.First[0]);
    		lapFileAddress.setText(agent.Third);


    		breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = agent.Fourth;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
    		
    	}
    }

    
    private void initPopupComponents()	{
        AttributeName = new javax.swing.JDialog();
        AttributeName.setResizable(false);
    	attributeNamePopUpTextBox = new javax.swing.JTextField();
        AttributeNamePopUpDoneButton = new javax.swing.JButton();
        AttributeNamePopUpCancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setText("Attribute Name: ");

        AttributeNamePopUpDoneButton.setText("Done");
        AttributeNamePopUpDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttributeNamePopUpDoneButtonActionPerformed(evt);
            }
        });

        AttributeNamePopUpCancelButton.setText("Cancel");
        AttributeNamePopUpCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttributeNamePopUpCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AttributeNameLayout = new javax.swing.GroupLayout(AttributeName.getContentPane());
        AttributeName.getContentPane().setLayout(AttributeNameLayout);
        AttributeNameLayout.setHorizontalGroup(
            AttributeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttributeNameLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AttributeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AttributeNameLayout.createSequentialGroup()
                        .addComponent(AttributeNamePopUpDoneButton)
                        .addGap(18, 18, 18)
                        .addComponent(AttributeNamePopUpCancelButton))
                    .addComponent(jLabel5)
                    .addComponent(attributeNamePopUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        AttributeNameLayout.setVerticalGroup(
            AttributeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttributeNameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeNamePopUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AttributeNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttributeNamePopUpDoneButton)
                    .addComponent(AttributeNamePopUpCancelButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        
        AttributeName.pack();
        AttributeName.setAlwaysOnTop(true);
    }
    
    
	private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        pluralBreedNameTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        singleBreedNameTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lapFileAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        breedAttributeListRemove = new javax.swing.JButton();
        breedAttributeListUp = new javax.swing.JButton();
        breedAttributeListAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        breedAttributeList = new javax.swing.JList<String>();
        jLabel4 = new javax.swing.JLabel();
        breedAttributeListDown = new javax.swing.JButton();
        AddAgentDoneButton = new javax.swing.JButton();
        AddAgentCancelButton = new javax.swing.JButton();
       
        
        
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Breed");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pluralBreedNameTextBox.setToolTipText("");

        jLabel1.setText("Breed Name (Must match the NetLogo plural e.g. wolves) ");

        jLabel2.setText("Single Breed Name (Must match the NetLogo single e.g. wolf) ");

        jLabel3.setText("LAP file");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        breedAttributeListRemove.setText("Remove");
        breedAttributeListRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedAttributeListRemoveActionPerformed(evt);
            }
        });

        breedAttributeListUp.setText("Up");
        breedAttributeListUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedAttributeListUpActionPerformed(evt);
            }
        });

        breedAttributeListAdd.setText("Add New");
        breedAttributeListAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedAttributeListAddActionPerformed(evt);
            }
        });

        breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Attributes" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        breedAttributeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(breedAttributeList);

        jLabel4.setText("Breed Attributes");

        breedAttributeListDown.setText("Down");
        breedAttributeListDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedAttributeListDownActionPerformed(evt);
            }
        });

        AddAgentDoneButton.setText("Done");
        AddAgentDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAgentDoneButtonActionPerformed(evt);
            }
        });

        AddAgentCancelButton.setText("Cancel");
        AddAgentCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAgentCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(AddAgentDoneButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddAgentCancelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(singleBreedNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(pluralBreedNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(breedAttributeListAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(breedAttributeListUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(breedAttributeListDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(breedAttributeListRemove))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lapFileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pluralBreedNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(singleBreedNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lapFileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breedAttributeListAdd)
                    .addComponent(breedAttributeListUp)
                    .addComponent(breedAttributeListRemove)
                    .addComponent(breedAttributeListDown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAgentDoneButton)
                    .addComponent(AddAgentCancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
           System.out.println("here");
        int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        lapFileAddress.setText(file.getAbsolutePath());
    }
    }                                        
                      
    
    private void breedAttributeListAddActionPerformed(java.awt.event.ActionEvent evt) {        
        initPopupComponents();                                              
        AttributeName.setVisible(true);
        
    }                     
    
	private void breedAttributeListUpActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        int selected = breedAttributeList.getSelectedIndex();
        if (selected <= 0)	{
        	
        }	else	{
        	//get all the current values
        	/*String[]*/ values = new String[breedAttributeList.getModel().getSize()];
        	for (int i = 0; i < values.length; i ++)	{
        		values[i] = breedAttributeList.getModel().getElementAt(i);
        	}
        	
        	//move the selected one up
        	String temp = values[selected-1];
        	values[selected-1] = values[selected];
        	values[selected] = temp;
        	
        	//reset the model
        	breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = values;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
        }
    }                                                    

	private void breedAttributeListDownActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        int selected = breedAttributeList.getSelectedIndex();
        if (selected == breedAttributeList.getModel().getSize()-1 || selected < 0)	{
        	
        }	else	{
        	//get all the current values
        	values = new String[breedAttributeList.getModel().getSize()];
        	for (int i = 0; i < values.length; i ++)	{
        		values[i] = breedAttributeList.getModel().getElementAt(i);
        	}
        	
        	//move the selected one down
        	String temp = values[selected+1];
        	values[selected+1] = values[selected];
        	values[selected] = temp;
        	
        	//reset the model
        	breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = values;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
        }
    }                                                      

	private void breedAttributeListRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selected = breedAttributeList.getSelectedIndex();
        if (selected < 0)	{
        	
        }	else if ( breedAttributeList.getModel().getElementAt(0).equalsIgnoreCase("Attributes"))	{
        	
        } else {
        	//get all the current values up to the selected one
        	values = new String[breedAttributeList.getModel().getSize()-1];
        	for (int i = 0; i < selected; i ++)	{
        		values[i] = breedAttributeList.getModel().getElementAt(i);
        	}
        	
        	//get all the values above the selected one
        	for (int i = selected+1; i < values.length+1; i ++)	{
        		values[i-1] = breedAttributeList.getModel().getElementAt(i);
        	}
        	
        	if (values.length == 0)	{
        		//must have at least 1 value
        		values = new String[] {"Attributes"};
        	}
        	
        	//reset the model
        	breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = values;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
        }
    }                                                        

    @SuppressWarnings("unchecked")
	private void AddAgentDoneButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    	if ((!singleBreedNameTextBox.getText().equalsIgnoreCase("")) ||
    		(!pluralBreedNameTextBox.getText().equalsIgnoreCase("")) ||
    		(!lapFileAddress.getText().equalsIgnoreCase("")))	{
    		String[] attributeArray = new String[breedAttributeList.getModel().getSize()];
    		for (int i = 0; i < attributeArray.length; i ++)	{
    			attributeArray[i] = breedAttributeList.getModel().getElementAt(i);
    		}
    		agent = new TupleFour<String[], Integer, String, String[]>
    		(new String[] {singleBreedNameTextBox.getText(), pluralBreedNameTextBox.getText()},
    				0, lapFileAddress.getText(), attributeArray);
    		TupleFour<String[], Integer, String, String[]> [] agentArray = 
    				new TupleFour [main.agents.length+1];
    		for (int i = 0; i < main.agents.length; i ++)	{
    			agentArray[i] = main.agents[i];
    		}
    		agentArray[main.agents.length] = agent;
    		main.agents = agentArray;
    		main.refreshBreedList();
    		this.setVisible(false);
    	} else	{
    		new Log("Add New Breed").error("Make sure all values are initialised");
    	}
    }                                                  

    private void AddAgentCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	this.setVisible(false);
    }                                                    

    private void AttributeNamePopUpDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {     
    	String newValue = attributeNamePopUpTextBox.getText(); 
    	if (newValue.replaceAll(" ", "").equalsIgnoreCase(""))	{
    		
    	}	else	{
    		//get the existing model, add the new value and set it
    		if (breedAttributeList.getModel().getElementAt(0).equalsIgnoreCase("Attributes"))	{
    			values = new String[1];
    		}	else	{
    			values = new String[breedAttributeList.getModel().getSize()+1];
    			for (int i = 0; i < values.length-1; i ++)	{
    				values[i] = breedAttributeList.getModel().getElementAt(i);
    			}
    		}
        	values[values.length-1] = newValue;
        	
        	//reset the model
        	breedAttributeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = values;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
        	AttributeName.setVisible(false);
    	}

    }                                                            

    private void AttributeNamePopUpCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
    	AttributeName.setVisible(false);
    }  

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton AddAgentCancelButton;
    private javax.swing.JButton AddAgentDoneButton;
    private javax.swing.JList<String> breedAttributeList;
    private javax.swing.JButton breedAttributeListAdd;
    private javax.swing.JButton breedAttributeListDown;
    private javax.swing.JButton breedAttributeListRemove;
    private javax.swing.JButton breedAttributeListUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lapFileAddress;
    private javax.swing.JTextField pluralBreedNameTextBox;
    private javax.swing.JTextField singleBreedNameTextBox;
    
    private javax.swing.JDialog AttributeName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField attributeNamePopUpTextBox;
    private javax.swing.JButton AttributeNamePopUpCancelButton;
    private javax.swing.JButton AttributeNamePopUpDoneButton;
    // End of variables declaration                   
}
