package gui;


import agentManager.AgentManager;





/*
 * This is part of the BODNetLogo program which integrates BOD with NetLogo,
 * please see the README files for this directory for more information
 * Michael Brooks
 */

/*
 * This code was originally auto generated by the NETBEANS IDE, gui creator.
 * The auto generator code only covers the positioning and specification of the GUI elements
 * The functionality of each element was later added manually
 */

@SuppressWarnings("serial")
public class SimulationController extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form SimulationController
     */
    public SimulationController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runModelButton = new javax.swing.JButton();
        runXTicksButton = new javax.swing.JButton();
        runXTicksTextBox = new javax.swing.JTextField();
        PauseModelButton = new javax.swing.JButton();
        //RestartModelButton = new javax.swing.JButton();
        //ReturnToSetupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 250));

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));

        runModelButton.setText("Run Model");
        runModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runModelButtonActionPerformed(evt);
            }
        });

        runXTicksButton.setText("Run x Ticks");
        runXTicksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runXTicksButtonActionPerformed(evt);
            }
        });

        PauseModelButton.setText("Pause Model");
        PauseModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseModelButtonActionPerformed(evt);
            }
        });

       /* RestartModelButton.setText("Restart");
        RestartModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartModelButtonActionPerformed(evt);
            }
        });*/

       /* ReturnToSetupButton.setText("Return To Setup");
        ReturnToSetupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnToSetupButtonActionPerformed(evt);
            }
        });*/
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runModelButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(runXTicksButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runXTicksTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PauseModelButton)
                    //.addComponent(RestartModelButton)
                    //.addComponent(ReturnToSetupButton))
                //.addContainerGap(47, Short.MAX_VALUE))
                    ))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runModelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runXTicksButton)
                    .addComponent(runXTicksTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PauseModelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                //.addComponent(RestartModelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                //.addComponent(ReturnToSetupButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 161, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void runModelButtonActionPerformed(java.awt.event.ActionEvent evt) {  
    	AgentManager.PAUSED = false;
    }                                              

    private void runXTicksButtonActionPerformed(java.awt.event.ActionEvent evt) {     
    	try	{
    		AgentManager.noTicks = Integer.parseInt(runXTicksTextBox.getText());
    		AgentManager.PAUSED = false;
    	}	catch (Exception e)	{
    		//incorrect input do nothing
    	}
    }                                               

    private void PauseModelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        AgentManager.PAUSED = true;
    }                                                

   /* private void RestartModelButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	try {
			App.app().open(BODNetLogo.nLogoModel);
    		//App.app(). = null;
	    	BODNetLogo.startSimManager();
		} catch (Exception e) {
			new Log("Simulation Controller").error("Unable to restart");
		}
    }                                                  

    private void ReturnToSetupButtonActionPerformed(java.awt.event.ActionEvent evt) {  
    	this.setVisible(false);
    	BODNetLogo.waitingForConfigInfo = true;
    	BODNetLogo.main(new String[0]);
    }    */                         

    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationController().*/this.setVisible(true);
          /*  }
        });*/
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton PauseModelButton;
    //private javax.swing.JButton RestartModelButton;
    //private javax.swing.JButton ReturnToSetupButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton runModelButton;
    private javax.swing.JButton runXTicksButton;
    private javax.swing.JTextField runXTicksTextBox;
    // End of variables declaration                   
}
